services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Admin\Administration\IngredientQuantityAdmin:
        class: App\Admin\Administration\IngredientQuantityAdmin
        arguments:
            - ~
            - App\Entity\IngredientQuantity
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: "administration_ingredient_quantity", label_translator_strategy: "App\\Translator\\ProjectLabelTranslatorStrategy" }

    App\Admin\Administration\RecipeImageAdmin:
        class: App\Admin\Administration\RecipeImageAdmin
        arguments:
            - ~
            - App\Entity\RecipeImage
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: "administration_recipe_image", label_translator_strategy: "App\\Translator\\ProjectLabelTranslatorStrategy" }

    App\Admin\Administration\IngredientAdmin:
        class: App\Admin\Administration\IngredientAdmin
        arguments:
            - ~
            - App\Entity\Ingredient
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: main, label: "administration_ingredient", label_translator_strategy: "App\\Translator\\ProjectLabelTranslatorStrategy" }

    App\Admin\Administration\RecipeAdmin:
        class: App\Admin\Administration\RecipeAdmin
        arguments:
            - ~
            - App\Entity\Recipe
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: main, label: "administration_recipe", label_translator_strategy: "App\\Translator\\ProjectLabelTranslatorStrategy" }

    App\Admin\Administration\SettingsAdmin:
        class: App\Admin\Administration\SettingsAdmin
        arguments:
            - ~
            - App\Entity\Settings
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: main, label: "administration_settings", label_translator_strategy: "App\\Translator\\ProjectLabelTranslatorStrategy" }

    App\Admin\Administration\UserAdministratorAdmin:
        class: App\Admin\Administration\UserAdministratorAdmin
        arguments:
            - ~
            - App\Entity\User
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: "administration_user_administrator", label_translator_strategy: "App\\Translator\\ProjectLabelTranslatorStrategy" }

    App\Admin\Administration\UserUserAdmin:
        class: App\Admin\Administration\UserUserAdmin
        arguments:
            - ~
            - App\Entity\User
            - App\Controller\CRUDUserController
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: "administration_user_user", label_translator_strategy: "App\\Translator\\ProjectLabelTranslatorStrategy" }