# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public_html"


    loaders:
        default:
            filesystem:
                data_root:
                - "%kernel.project_dir%/public_html/"
                - "%kernel.project_dir%/public_html/uploads/ingredients/"
                - "%kernel.project_dir%/public_html/uploads/recipeImages/"

    filter_sets:
        cache: ~

        admin_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }

        admin_preview:
            quality: 75
            filters:
                thumbnail: { size: [480, 320], mode: outbound }

        recipe_main_image:
            quality: 90
            filters:
                thumbnail: { size: [480, 320], mode: outbound }

        recipe_ingredient:
            quality: 75
            filters:
                thumbnail: { size: [90, 60], mode: outbound }
