sonata_admin:
    title: 'Panel'
    title_logo: '/images/icon.png'
    dashboard:
        groups:
            main:
                label: "administration.groups.main"
                keep_open: true
            user:
                label: "administration.groups.user"

        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        layout: 'admin/layout.html.twig'
    assets:
        extra_stylesheets:
            - 'css/sonata_custom.css'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
