vich_uploader:
    db_driver: orm

    mappings:
        ingredient:
            uri_prefix: /uploads/ingredients
            upload_destination: '%kernel.project_dir%/public/uploads/ingredients'
            namer: vich_uploader.namer_uniqid
